// src/lib/email/sites.ts
// Per-brand configuration. All env vars are read at module load (server-side only).

import type { SiteConfig } from "./types";

export const SITES: Record<string, SiteConfig> = {
  abeevis: {
    siteId: "abeevis",
    businessName: "Abeevis",
    recipientEmail:
      process.env.ABEEVIS_EMAIL || process.env.AGENCY_EMAIL || "",
    allowedOrigins: ["https://abeevis.com", "https://www.abeevis.com"],
    servicesLabel: "Service Requested",
    leadIdPrefix: "ABV",
    customerLang: "en",
    supportPhone: process.env.ABEEVIS_PHONE || "",
    whatsappNumber: process.env.ABEEVIS_WHATSAPP || "",
    displayPhone: process.env.ABEEVIS_DISPLAY_PHONE || "",
    urgentServices: [], // digital agency — nothing is roadside-urgent
    brand: {
      theme: "studio",
      primaryColor: "#2B2B2B",
      secondaryColor: "#F8F5EF",
      accentColor: "#8A5A18",
      backgroundColor: "#F7F3EA",
      cardColor: "#FFFFFF",
      textColor: "#2B2B2B",
      mutedTextColor: "#6B665E",
      borderColor: "#E8DFD2",
      logoStyle: "image",
      logoText: "ABEEVIS",
      websiteUrl: "https://www.abeevis.com",
      tagline: "Digital clarity. Engineered creativity.",
      eyebrow: "ABEEVIS STUDIO",
      ctaLabel: "Reply to Lead",
    },
  },

  "family-transport": {
    siteId: "family-transport",
    businessName: "Family Transport USA",
    recipientEmail: process.env.FAMILY_TRANSPORT_EMAIL || "",
    allowedOrigins: [
      "https://familytransportusa.com",
      "https://www.familytransportusa.com",
    ],
    servicesLabel: "Servicio Solicitado",
    leadIdPrefix: "FTU",
    customerLang: "es",
    supportPhone: process.env.FAMILY_TRANSPORT_PHONE || "",
    whatsappNumber: process.env.FAMILY_TRANSPORT_WHATSAPP || "",
    displayPhone: process.env.FAMILY_TRANSPORT_DISPLAY_PHONE || "",
    urgentServices: [
      "Towing",
      "Grúa",
      "Grua",
      "Roadside",
      "asistencia en carretera",
      "Door unlocking",
      "Apertura",
      "Fuel delivery",
      "combustible",
      "Tire change",
      "neumático",
      "neumatico",
    ],
    brand: {
      theme: "roadside",
      primaryColor: "#090D12",
      secondaryColor: "#111827",
      accentColor: "#EF233C",
      backgroundColor: "#070A0F",
      cardColor: "#10151D",
      textColor: "#FFFFFF",
      mutedTextColor: "#CBD5E1",
      borderColor: "#252B36",
      logoStyle: "image",
      logoUrl: "https://www.abeevis.com/email-assets/family-transport-logo.png",
      websiteUrl: "https://www.familytransportusa.com",
      tagline: "Asistencia vial rápida, directa y confiable.",
      eyebrow: "SOLICITUD DE SERVICIO",
      ctaLabel: "Responder al cliente",
    },
  },

  "vr-enterprise": {
    siteId: "vr-enterprise",
    businessName: "VR Enterprise",
    recipientEmail: process.env.VR_ENTERPRISE_EMAIL || "",
    allowedOrigins: ["https://vr-enterprise-sigma.vercel.app"],
    servicesLabel: "Servicio / Equipo Solicitado",
    leadIdPrefix: "VRE",
    customerLang: "es",
    supportPhone: process.env.VR_ENTERPRISE_PHONE || "",
    whatsappNumber: process.env.VR_ENTERPRISE_WHATSAPP || "",
    displayPhone: process.env.VR_ENTERPRISE_DISPLAY_PHONE || "",
    urgentServices: [], // B2B quotes — typically not time-critical
    brand: {
      theme: "industrial",
      primaryColor: "#050505",
      secondaryColor: "#111111",
      accentColor: "#FACC15",
      backgroundColor: "#080808",
      cardColor: "#111111",
      textColor: "#FFFFFF",
      mutedTextColor: "#C7C7C7",
      borderColor: "#2A2A2A",
      logoStyle: "image",
      logoUrl: "https://www.abeevis.com/email-assets/vr-enterprise-logo.png",
      websiteUrl: "https://vr-enterprise-sigma.vercel.app",
      tagline: "Infraestructura • Energía • Logística • Tecnología",
      eyebrow: "NUEVA COTIZACIÓN",
      ctaLabel: "Responder solicitud",
    },
  },
};
